/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VolBank;

import org.junit.Test;

import org.junit.Before;

public class AppTest {
OrganizacionVoluntarios u1;

    @Before public void setUp(){
    u1 = new OrganizacionVoluntarios("Hogar para el adulto mayor", "80091","Cocinero");
    }

    @Test public void testRegistroNecesidad() {
        Necesidad classUnderTest = new Necesidad(001, "12/17/2020", "01/17/2020", u1);
        classUnderTest.push();
        System.out.print(classUnderTest.toString());
    }
}
